[build]
  command = "npm run build"
  publish = ".next"
  base = "/"

  ignore = "false"  # Never skip build
  force = "true"    # Force build even if no changes detected

[build.environment]
  NODE_VERSION = "20"
  CI = "true"       # Ensure we're in CI mode
  NETLIFY_BUILD_SKIP = "false"  # Never skip build
  NEXT_PUBLIC_SITE_URL = "https://limitlessinfotech.com"

[build.processing]
  skip_processing = false  # Ensure processing is not skipped

[dev]
  command = "npm run dev"
  port = 3000
  publish = ".next"
